---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rykonden/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R UAS $DEPLOYPATH
    - /bin/cp -R style $DEPLOYPATH
